type: google.api.Service
config_version: 3

http:
  rules:
    - selector: grpcproto.ExampleGetService.ExampleGetHandler
      get: /example/get
    - selector: grpcproto.ExamplePostService.ExamplePostHandler
      post: /example/post
      body: "*"